<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BT9B872" failures="2" tests="4" name="Test" time="1.322" errors="0" timestamp="2021-12-17T20:29:10 IST">
  <testcase classname="testNGFramework.ExecuteFailedTestINTestNG" name="test1" time="0.1"/>
  <testcase classname="testNGFramework.ExecuteFailedTestINTestNG" name="test2" time="0.102">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGFramework.ExecuteFailedTestINTestNG.test2(ExecuteFailedTestINTestNG.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testNGFramework.ExecuteFailedTestINTestNG" name="test3" time="0.015"/>
  <testcase classname="testNGFramework.ExecuteFailedTestINTestNG" name="test4" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGFramework.ExecuteFailedTestINTestNG.test4(ExecuteFailedTestINTestNG.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
</testsuite> <!-- Test -->
